application: search-engine
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /pictures
  static_dir: pictures

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

